# Generated by Django 3.2.6 on 2021-08-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robottutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='editorCode',
            field=models.CharField(max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='robotAPI',
            field=models.CharField(max_length=30000, null=True),
        ),
    ]
