# Generated by Django 3.2.6 on 2021-09-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robottutor', '0002_auto_20210831_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='passcodeguiapp',
            field=models.CharField(max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='passcodewebapp',
            field=models.CharField(max_length=30000, null=True),
        ),
    ]
